package io.github.jwolff52.rankup.util;

import io.github.jwolff52.rankup.RankUp;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.logging.Logger;

import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerJoinEvent;

public class RankUpListener implements Listener{
	public static RankUp plugin;
	
	public static ArrayList<String> defaults;
	
	public RankUpListener(RankUp instance){
		plugin=instance;
		defaults=new ArrayList<String>();
		defaults.add("# This is the configuration file for the player, DO NOT edit this file for any reason as it may break the plugin");
		defaults.add("CurrentGroup:1");
	}
	
	@EventHandler
	public void onPlayerJoin(PlayerJoinEvent e){
		File n=new File(new File(plugin.getDataFolder(), "players"), e.getPlayer().getUniqueId()+".yml");
		if(!n.exists()){
			try {
				n.createNewFile();
			}catch(IOException e1){
				e1.printStackTrace();
			}
			try {
				Files.write(n.toPath(), defaults, StandardCharsets.UTF_8);
			} catch (IOException e1) {
				e1.printStackTrace();
			}
			plugin.addPlayerFile(n);
			Logger.getLogger("Minecraft").info("RankUp - INFO - Player file created for "+e.getPlayer().getName()+"!");
		}else{
			Logger.getLogger("Minecraft").info("RankUp - INFO - "+e.getPlayer().getName()+" has played before! No file created!");
		}
	}
}
